---
title: "OrganizeData"
author: "Giuseppe Pontillo"
date: '2024-11'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/data/anw/knw-work/g.pontillo/predictive_modelling/code/stats/AtrophyModelling")
packages <- c("dplyr", "ggplot2", "here", "nlme", "mgcv", "MuMIn", "gratia", "rsample", "gamclass", "purrr", "broom", "mgcViz", "Metrics", "cowplot")
lapply(packages, library, character.only = TRUE)
```

```{r import and transform data for GAM modelling, purl = FALSE}
# atrophy rates
atrophy_long <- read.csv(here::here("data/atrophy_long/atrophy_long_SchaeferSubcortex114Parcels_individual_slopes.csv"), header = TRUE, sep = ",")

df <- data.frame(matrix(nrow = 0, ncol = 3))
colnames(df) <- c("atrophy_rate", "node", "id")
for (i in 1:dim(atrophy_long)[1]){
  rates <- as.data.frame(t(atrophy_long[i,-1]))
  rates <- tibble::rownames_to_column(rates)
  rates$id <- rep(atrophy_long[i,1],114)
  colnames(rates) <- c("node", "atrophy_rate", "id")
  rates$node <- gsub("_slope", "", rates$node)
  df <- rbind(df, rates)
}

# baseline atrophy
atrophy_cross <- read.csv(here::here("data/atrophy_cross/atrophy_baseline_SchaeferSubcortex114Parcels_individuals_wscore.csv"), header = TRUE, sep = ",")

df_atrophy_bl <- data.frame(matrix(nrow = 0, ncol = 3))
colnames(df_atrophy_bl) <- c("atrophy_bl", "node", "id")
for (i in 1:dim(atrophy_cross)[1]){
  atrophy_bl <- as.data.frame(t(atrophy_cross[i,-1]))
  atrophy_bl <- tibble::rownames_to_column(atrophy_bl)
  atrophy_bl$id <- rep(atrophy_cross[i,1],114)
  colnames(atrophy_bl) <- c("node", "atrophy_bl", "id")
  atrophy_bl$node <- gsub("_wscore", "", atrophy_bl$node)
  df_atrophy_bl <- rbind(df_atrophy_bl, atrophy_bl)
}
df <- merge(df, df_atrophy_bl, by = c("node", "id"))

# structural centrality
sc_matrix_ctx <- read.csv(here::here("data/hcp_connectivity/strucMatrix_ctx_schaefer_100.csv"), header = FALSE, sep = ",")
sc_centrality_ctx <- rowSums(sc_matrix_ctx)
sc_matrix_sctx <- read.csv(here::here("data/hcp_connectivity/strucMatrix_sctx_schaefer_100.csv"), header = FALSE, sep = ",")
sc_matrix_sctx <- sc_matrix_sctx[,1:100]
sc_centrality_sctx <- rowSums(sc_matrix_sctx)
sc_centrality <- as.data.frame(c(sc_centrality_ctx, sc_centrality_sctx))
colnames(sc_centrality) <- "sc_centrality"
sc_centrality$node <- gsub("_slope", "", colnames(atrophy_long[,-1]))

df <- merge(df, sc_centrality, by = c("node"))

# functional centrality
fc_matrix_ctx <- read.csv(here::here("data/hcp_connectivity/funcMatrix_ctx_schaefer_100.csv"), header = FALSE, sep = ",")
fc_centrality_ctx <- rowSums(fc_matrix_ctx)
fc_matrix_sctx <- read.csv(here::here("data/hcp_connectivity/funcMatrix_sctx_schaefer_100.csv"), header = FALSE, sep = ",")
fc_centrality_sctx <- rowSums(fc_matrix_sctx)
fc_centrality <- as.data.frame(c(fc_centrality_ctx, fc_centrality_sctx))
colnames(fc_centrality) <- "fc_centrality"
fc_centrality$node <- gsub("_slope", "", colnames(atrophy_long[,-1]))

df <- merge(df, fc_centrality, by = c("node"))

# parcel disconnection
disc_vector_ctx <- read.csv(here::here("data/disc/disc_SchaeferSubcortex114Parcels_individuals_ctx.csv"), header = TRUE, sep = ",")
disc_vector_sctx <- read.csv(here::here("data/disc/disc_SchaeferSubcortex114Parcels_individuals_sctx.csv"), header = TRUE, sep = ",")
df_disc <- as.data.frame(matrix(nrow = 0, ncol = 3))
colnames(df_disc) <- c("id","node","disc")
for (i in 1: dim(disc_vector_ctx)[1]){
  disc_matrix <- matrix(0,nrow = 100, ncol = 100)
  disc_matrix[upper.tri(disc_matrix)] <- unlist(disc_vector_ctx[i,-1])
  disc_matrix[lower.tri(disc_matrix)] <- t(disc_matrix[lower.tri(disc_matrix)])
  disc_ctx <- rowSums(disc_matrix)
  disc_matrix_sctx <- matrix(unlist(disc_vector_sctx[i,-1]), 14, 100)
  disc_sctx <- rowSums(disc_matrix_sctx)
  disc <- data.frame(matrix(nrow = 114, ncol = 3))
  colnames(disc) <- c("id","node","disc")
  disc$disc <- c(disc_ctx, disc_sctx)
  disc$id <- rep(gsub("_ses-01|_ses-Y05", "",disc_vector_ctx[i,1]),114)
  disc$node <- gsub("_slope", "", colnames(atrophy_long[,-1]))
  df_disc <- rbind(df_disc, disc)
}

df <- merge(df, df_disc, by = c("id", "node"))

# structural neighbourhood atrophy
neighbourhood_atrophy_sc_ctx <- read.csv(here::here("data/neighbourhood_atrophy/neighbourhood_atrophy_cross_SchaeferSubcortex114Parcels_individuals_sc_ctx.csv"), header = TRUE, sep = ",")
neighbourhood_atrophy_sc_sctx <- read.csv(here::here("data/neighbourhood_atrophy/neighbourhood_atrophy_cross_SchaeferSubcortex114Parcels_individuals_sc_sctx.csv"), header = TRUE, sep = ",")
neighbourhood_atrophy_sc <- merge(neighbourhood_atrophy_sc_ctx,neighbourhood_atrophy_sc_sctx, by = "id")

df_neighbourhood_atrophy_sc <- data.frame(matrix(nrow = 0, ncol = 3))
colnames(df_neighbourhood_atrophy_sc) <- c("neighbourhood_atrophy_sc", "node", "id")
for (i in 1:dim(neighbourhood_atrophy_sc)[1]){
  atrophy_sc <- as.data.frame(t(neighbourhood_atrophy_sc[i,-1]))
  atrophy_sc <- tibble::rownames_to_column(atrophy_sc)
  atrophy_sc$id <- rep(neighbourhood_atrophy_sc[i,1],114)
  colnames(atrophy_sc) <- c("node", "neighbourhood_atrophy_sc", "id")
  atrophy_sc$node <- gsub("_wscore_neighbours", "", atrophy_sc$node)
  df_neighbourhood_atrophy_sc <- rbind(df_neighbourhood_atrophy_sc, atrophy_sc)
}
df <- merge(df, df_neighbourhood_atrophy_sc, by = c("node", "id"))

# functional neighbourhood atrophy
neighbourhood_atrophy_fc_ctx <- read.csv(here::here("data/neighbourhood_atrophy/neighbourhood_atrophy_cross_SchaeferSubcortex114Parcels_individuals_fc_ctx.csv"), header = TRUE, sep = ",")
neighbourhood_atrophy_fc_sctx <- read.csv(here::here("data/neighbourhood_atrophy/neighbourhood_atrophy_cross_SchaeferSubcortex114Parcels_individuals_fc_sctx.csv"), header = TRUE, sep = ",")
neighbourhood_atrophy_fc <- merge(neighbourhood_atrophy_fc_ctx,neighbourhood_atrophy_fc_sctx, by = "id")

df_neighbourhood_atrophy_fc <- data.frame(matrix(nrow = 0, ncol = 3))
colnames(df_neighbourhood_atrophy_fc) <- c("neighbourhood_atrophy_fc", "node", "id")
for (i in 1:dim(neighbourhood_atrophy_fc)[1]){
  atrophy_fc <- as.data.frame(t(neighbourhood_atrophy_fc[i,-1]))
  atrophy_fc <- tibble::rownames_to_column(atrophy_fc)
  atrophy_fc$id <- rep(neighbourhood_atrophy_fc[i,1],114)
  colnames(atrophy_fc) <- c("node", "neighbourhood_atrophy_fc", "id")
  atrophy_fc$node <- gsub("_wscore_neighbours", "", atrophy_fc$node)
  df_neighbourhood_atrophy_fc <- rbind(df_neighbourhood_atrophy_fc, atrophy_fc)
}
df <- merge(df, df_neighbourhood_atrophy_fc, by = c("node", "id"))

# GE neighbour atrophy
neighbourhood_atrophy_cge_ctx <- read.csv(here::here("data/neighbourhood_atrophy/neighbourhood_atrophy_cross_SchaeferSubcortex114Parcels_individuals_cge_ctx.csv"), header = TRUE, sep = ",")
neighbourhood_atrophy_cge_sctx <- read.csv(here::here("data/neighbourhood_atrophy/neighbourhood_atrophy_cross_SchaeferSubcortex114Parcels_individuals_cge_sctx.csv"), header = TRUE, sep = ",")
neighbourhood_atrophy_cge <- merge(neighbourhood_atrophy_cge_ctx,neighbourhood_atrophy_cge_sctx, by = "id")

df_neighbourhood_atrophy_cge <- data.frame(matrix(nrow = 0, ncol = 3))
colnames(df_neighbourhood_atrophy_cge) <- c("neighbourhood_atrophy_cge", "node", "id")
for (i in 1:dim(neighbourhood_atrophy_cge)[1]){
  atrophy_cge <- as.data.frame(t(neighbourhood_atrophy_cge[i,-1]))
  atrophy_cge <- tibble::rownames_to_column(atrophy_cge)
  atrophy_cge$id <- rep(neighbourhood_atrophy_cge[i,1],114)
  colnames(atrophy_cge) <- c("node", "neighbourhood_atrophy_cge", "id")
  atrophy_cge$node <- gsub("_wscore_neighbours", "", atrophy_cge$node)
  df_neighbourhood_atrophy_cge <- rbind(df_neighbourhood_atrophy_cge, atrophy_cge)
}
df <- merge(df, df_neighbourhood_atrophy_cge, by = c("node", "id"))

# coordinates
coords <- read.csv(here::here("data/Schaefer100_Subcortex_coords.csv"), header = FALSE, sep = ",")

df_coords <- data.frame(matrix(nrow = 114, ncol = 4))
colnames(df_coords) <- c("node", "x", "y", "z")

df_coords$node <- gsub("_slope", "", colnames(atrophy_long[,-1]))
df_coords[,2:4] <- coords[,3:5]
df <- merge(df, df_coords, by = "node")

# cortical/subcortical
df <- df %>% mutate(subcortical = case_when (
  grepl("network", node) ~ "0",
  !grepl("network", node) ~ "1")) 

# add age and sex
df_baseline <- read.csv(here::here("data/df_baseline.csv"), header = TRUE, sep = ",")
age_sex <- df_baseline[,c("id", "age", "sex")]
df <- merge(df, age_sex, by = "id")

# fu time duration and site
df_long <- read.csv(here::here("data/df_long.csv"), header = TRUE, sep = ",")
df_long <- df_long %>% group_by(id) %>% mutate(fu_time_duration = fu_time[which.max(fu_time)]) %>% ungroup()
fu_time_duration_site <- df_long[,c("id", "fu_time_duration", "site")]
df <- merge(df, fu_time_duration_site, by = "id")

# write out
write.csv(df, here::here("data/df_GAM.csv"), row.names = FALSE)
```


```{r GAM modelling}
## import and transform
df_GAM <- read.csv(here::here("data/df_GAM.csv"), header = TRUE, sep = ",")

df_GAM$node <- as.factor(df_GAM$node)
df_GAM$id <- as.factor(df_GAM$id)
df_GAM$subcortical <- as.factor(df_GAM$subcortical)
df_GAM$sex <- as.factor(df_GAM$sex)
df_GAM$site <- as.factor(df_GAM$site)

## model fitting and comparison
model_gam <- bam(atrophy_rate ~ s(atrophy_bl) + s(sc_centrality) + s(fc_centrality) + s(disc) + s(neighbourhood_atrophy_sc) + s(neighbourhood_atrophy_fc) + s(neighbourhood_atrophy_cge) + s(x,y,z) + s(age) + s(fu_time_duration) + sex + subcortical + site + s(id, bs = 're') + s(node, bs = 're') + s(atrophy_bl, node, bs = 're'), data = df_GAM, na.action = na.fail, method = "fREML", select = TRUE, discrete = FALSE,nthreads = 8)

model_gam_bl <- bam(atrophy_rate ~ s(atrophy_bl) + s(x,y,z) + s(age) + s(fu_time_duration) + sex + subcortical + site + s(id, bs = 're') + s(node, bs = 're') + s(atrophy_bl, node, bs = 're'), data = df_GAM, na.action = na.fail, method = "fREML", select = TRUE, discrete = FALSE, nthreads = 8)

anova_test <- anova(model_gam_bl, model_gam, test = "LRT")
AIC_test <- AIC(model_gam_bl, model_gam)

# save
save(model_gam, model_gam_bl, anova_test, AIC_test, file = here("data/GAM_modelling.RData"))

## LOOCV
custom_cvparts <- group_vfold_cv(df_GAM, group = id)

mod_form <- as.formula(atrophy_rate ~ s(atrophy_bl) + s(sc_centrality) + s(fc_centrality) + s(disc) + s(neighbourhood_atrophy_sc) + s(neighbourhood_atrophy_fc) + s(neighbourhood_atrophy_cge) + s(x,y,z) + s(age) + s(fu_time_duration) + sex + subcortical + site + s(id, bs = 're') + s(node, bs = 're') + s(atrophy_bl, node, bs = 're')) 

mod_form_bl <- as.formula(atrophy_rate ~ s(atrophy_bl) + s(x,y,z) + s(age) + s(fu_time_duration) + sex + subcortical + site + sex + subcortical + s(id, bs = 're') + s(node, bs = 're') + s(atrophy_bl, node, bs = 're')) 
  
holdout_results <- function(splits, ...){
  # fit the model
  mod <- bam(..., data = analysis(splits), na.action = na.fail, method = "fREML", select = TRUE, discrete = TRUE, nthreads = 8)
  # apply the model and assess performance
  holdout <- assessment(splits)
  res <- broom::augment(mod, newdata = holdout)
  performance <- data.frame(matrix(nrow = 1, ncol = 3))
colnames(performance) <- c("pearsonr", "RMSE", "MAE")
  performance$pearsonr <- cor(res$.fitted, holdout$atrophy_rate, method = "pearson")
  performance$RMSE <- rmse(holdout$atrophy_rate, res$.fitted)
  performance$MAE <- mae(holdout$atrophy_rate, res$.fitted)
  output <- list(res, performance)
  # return output
  return(output)
}

# example <- holdout_results(custom_cvparts$splits[[1]], mod_form)

LOOCV <- purrr::map(custom_cvparts$splits, holdout_results, mod_form)

LOOCV_bl <- purrr::map(custom_cvparts$splits, holdout_results, mod_form_bl)

# save
save(LOOCV, LOOCV_bl, file = here("data/GAM_LOOCV.RData"))

## LOOCV CVgam
# custom_cvparts <- rep(1:565, each = 114)
# 
# LOOCV <- CVgam(formula = atrophy_rate ~ s(atrophy_bl) + s(sc_centrality) + s(fc_centrality) + s(disc) + s(neighbourhood_atrophy_sc) + s(neighbourhood_atrophy_fc) + s(neighbourhood_atrophy_cge) + s(x,y,z) + s(age) + sex + subcortical + s(id, bs = 're') + s(node, bs = 're') + s(atrophy_bl, node, bs = 're'), data = df_GAM, printit = TRUE, method = "GCV.Cp", cvparts = custom_cvparts, seed = 42)

# LOOCV_bl <- CVgam(formula = atrophy_rate ~ s(atrophy_bl) + s(x,y,z) + s(age) + sex + subcortical + s(id, bs = 're') + s(node, bs = 're') + s(atrophy_bl, node, bs = 're'), data = df_GAM, printit = TRUE, method = "GCV.Cp", cvparts = custom_cvparts, seed = 42)
# 
# # save
# save(LOOCV_bl, file = here("data/LOOCV_bl.RData"))

## model selection with MuMIn
# model_selection <- dredge(model_gam, evaluate = TRUE, fixed = ~ s(atrophy_bl) + s(x,y,z) + s(age) + sex + subcortical + s(id, bs = 're') + s(node, bs = 're') + s(node, atrophy_bl, bs = 're'))

# best_model <- get.models(model_selection, 1)[[1]]

```

```{r visualize GAM models, purl = FALSE}
# load data
load(here("data/GAM_modelling.RData"))

# model diagnostics
check_GAM <- appraise(model_gam)
ggsave(here("data/check_GAM.png"), plot = check_GAM, dpi = 300)

b <- getViz(model_gam)
png(file=here("data/plot_GAM.png"), width = 8000, height = 8000, res = 600)
print(plot(b, allTerms = TRUE), pages = 1) 
dev.off()


GAM_all <- cowplot::plot_grid(plot_GAM[[1]][[1]],plot_GAM[[1]][[2]],plot_GAM[[1]][[3]],plot_GAM[[1]][[4]],plot_GAM[[1]][[5]],plot_GAM[[1]][[6]],plot_GAM[[1]][[7]],plot_GAM[[1]][[8]],plot_GAM[[1]][[9]],plot_GAM[[1]][[10]],plot_GAM[[1]][[11]],plot_GAM[[1]][[12]],plot_GAM[[1]][[13]],plot_GAM[[1]][[14]],plot_GAM[[1]][[15]],labels="AUTO",label_size=24, nrow = 3, ncol = 5)
ggsave(here("data/plot_GAM.png"), plot = GAM_all, height = 35, width = 21)
plot_GAM <- draw(model_gam, residuals = TRUE)
plot_GAM <- plot(model_gam)
ggsave(here("data/plot_GAM.png"), plot = plot_GAM, dpi = 300)

sm <- smooth_estimates(model_gam)

sm |> add_confint() |> ggplot(aes(y = .estimate, x = atrophy_bl)) +
  geom_ribbon(aes(ymin = .lower_ci, ymax = .upper_ci), alpha = 0.2, fill = "blue") +
  geom_line(colour = "black", linewidth = 1.5) +
  labs(y = "Partial effect", x = "Baseline atrophy", title = "Partial effect of baseline atrophy")

# load data
load(here("data/GAM_LOOCV.RData"))

mean_pearsonr <- hist(unlist(lapply(lapply(LOOCV, '[[', 2), '[[', "pearsonr")))

mean_rmse <- mean(unlist(lapply(lapply(LOOCV_bl, '[[', 2), '[[', "RMSE")))

```










